use_frameworks!

platform :ios, '15.5'

target 'GCLocation_Example' do
  pod 'GCLocationPOD', :path => '../'

  target 'GCLocation_Tests' do
    inherit! :search_paths

    
  end
  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
                 end
            end
     end
  end
end
